Add data parsing and model fitting functions
InsightRX/irxadmiral pull request #2
Opened 2023-10-05 21:42 UTC by roninsightrx

Added functionality to parse SDTM data tables to a NONMEM-style dataset.
Also included basic functionality for running nlmixr2 and outputting GOF plots.

2023-10-05 23:49 UTC, karawoo requested changes
I was requested to give a quick check and not a full review, so I've tried to focus mainly on aspects that will affect 1) the ability to install/run the package as written, 2) safe management of DB connections, and 3) legal/licensing considerations. I also have not actually been able to run the modeling steps as I cannot get nlmixr2 to run on either my M1 mac nor on our linux server.

I have not reviewed design decisions except for in `create_db_connection()` where I have a question about passing the DB credentials as a list instead  of env vars.

I know you're not planning to write tests in this PR, but I strongly feel that we should write them soon.

2023-10-05 23:49 UTC, karawoo commented on R/create_db_connection.R
> +  db
What is the reason to pass this as a list instead of using env vars?

2023-10-05 23:49 UTC, karawoo commented on R/parse_data_for_modelfit.R
> +  ## https://github.com/pharmaverse/admiral/blob/main/inst/templates/ad_adppk.R
We may need to include a copy of the admiral license here if we are redistributing a derivative work:

https://github.com/pharmaverse/admiral/blob/main/LICENSE.md#4-redistribution

2023-10-05 23:49 UTC, karawoo commented on DESCRIPTION
> +    tibble,
```suggestion
```
Not used as far as I can tell?

2023-10-05 23:49 UTC, karawoo commented on R/run_sql_query.R
> +  DBI::dbDisconnect(conn)
```suggestion
  conn <- create_db_connection(db) # for now, we will not try to persist the connection
  on.exit(DBI::dbDisconnect(conn))
  result <- DBI::dbGetQuery(
    conn = conn, 
    statement = query
  )
```

2023-10-05 23:49 UTC, karawoo commented on R/parse_data_for_modelfit.R
> +      -ends_with("TMF"), -starts_with("TRT"), -starts_with("ATPT"), -DRUG
These need to either be prefixed with `tidyselect::` or put `#' @importFrom tidyselect starts_with ends_with` in the roxygen comments and re-document.

2023-10-06 17:56 UTC, roninsightrx commented on DESCRIPTION
> +    tibble,
yes, I removed the tibble function call as it was only used once.

2023-10-06 17:57 UTC, roninsightrx commented on R/create_db_connection.R
> +  db
I don't think they are available as env vars. Can discuss more on Slack.

2023-10-06 19:53 UTC, karawoo commented on R/parse_data_for_modelfit.R
> +        creat = CREATBL, creatu = "SI", age = AGE, wt = WTBL, sex = SEX,
```suggestion
        creat = CREATBL, creatu = "SI", age = AGE, weight = WTBL, sex = SEX,
```
I missed another instance of this deprecated argument in my first review

2023-10-06 19:53 UTC, karawoo commented on R/misc.R
> +`%>%` <- dplyr::`%>%`
This will create a build-time dependency which is probably not what we want. The pipe should instead be imported in a roxygen comment:
```
#' @importFrom dplyr %>%
```

2023-10-06 19:53 UTC, karawoo commented on run_modelfit.R
Doesn't affect the functioning of the package, but this different version of `run_modelfit()` is still here outside of `R/`.

2023-10-06 19:53 UTC, karawoo commented on .Rbuildignore
> +^\.Rproj\.user$
```suggestion
^\.Rproj\.user$
LICENSE-admiral.md
```

2023-10-06 21:12 UTC, karawoo commented on .Rbuildignore
> +^\.Rproj\.user$
Actually, that might not be the right thing to do because then the license won't be included in the built package. I'm not sure if that meets the license terms or not. We could leave it out of .Rbuildignore, or put the license text in comments in the code.

2023-10-06 21:43 UTC, roninsightrx commented on .Rbuildignore
> +^\.Rproj\.user$
i think it's fine for now. Pretty soon I want to refactor the example that I took from the admiral packagel anyhow to be more generic and not follow exactly the example they provided. So going forward we wouldn't have to provide the license file.

2023-10-06 23:27 UTC, karawoo requested changes
Discussed further in slack, but the code should use lowercase column names

2023-10-06 23:29 UTC, roninsightrx commented on R/parse_data_for_modelfit.R
> +        weight = WTBL,
bug in original template code

2023-10-09 16:36 UTC, karawoo approved these changes

2023-10-09 16:40 UTC, merged