CHAT-136 Add NCA functionality, and infer route from data
InsightRX/irxadmiral pull request #3
Opened 2023-10-12 05:24 UTC by roninsightrx

This adds functionality for parsing SDTM to data suitable for IQnca package.
It also infers the route from the data, both for NCA and modeling analysis, instead of having user supply the route.

2023-10-12 05:28 UTC, roninsightrx commented on R/parse_data_for_modelfit.R
> -      ROUTE = "oral",    # TODO: hardcoded for now
we actually didn't need it here, this is the temporary table holding the covariates.

2023-10-12 05:28 UTC, roninsightrx commented on R/parse_data_for_modelfit.R
> +      FORM = EXDOSFRM
we want to add ROUTE and FORM to all dosing rows. For all observations the values in these columsn will be NA, which is intended.

2023-10-12 18:17 UTC, karawoo requested changes
A couple of small comments, there are also some documentation mismatches right now but that's not an issue that would affect running the code.

2023-10-12 18:17 UTC, karawoo commented on R/parse_data_for_nca.R
> +    setNames(toupper(names(.))) %>%
```suggestion
    stats::setNames(toupper(names(.))) %>%
```

2023-10-12 18:17 UTC, karawoo commented on R/parse_data_for_nca.R
> +      setNames(toupper(names(.))) %>%
```suggestion
      stats::setNames(toupper(names(.))) %>%
```

2023-10-13 04:26 UTC, karawoo approved these changes

2023-10-13 04:58 UTC, merged