allow simulation from fitted model
InsightRX/irxadmiral pull request #4
Opened 2023-10-18 21:02 UTC by roninsightrx

This implements functionality for simulation from a fitted model (fitted using nlmixr2).

2023-10-18 21:04 UTC, roninsightrx commented on R/run_simulation.R
> +    dat$y <- PKPDsim::add_ruv(dat$y, list(add = add_sd, prop = prop_sd))
could just port over this simple function into irxadmiral, but most likely we'll be using PKPDsim for other things in the future as well, so not a problem to make it a dependency IMO.

2023-10-18 22:08 UTC, karawoo requested changes
We should add `rxode2` to the DESCRIPTION. Just a few other minor comments.

2023-10-19 19:44 UTC, roninsightrx commented on R/run_simulation.R
> +#' @param scenarios list of lists, with inner list having `dose` and `interval`
It's from an earlier version. removing.

2023-10-23 17:07 UTC, karawoo approved these changes

2023-10-23 17:08 UTC, merged