CHAT-176 and CHAT-174 fixes and updates to demographics table
InsightRX/irxadmiral pull request #7
Opened 2023-11-01 20:30 UTC by roninsightrx

2023-11-01 23:03 UTC, karawoo requested changes

2023-11-01 23:03 UTC, karawoo commented on R/create_demographics_table.R
> +        merge(vitals)
I am seeing different counts when I run the function for variables that are in `dm` only vs. when I run it for variables that are split across `dm` and `vs`. I think the reason is that we have some subject IDs in `dm` that aren't in `vs`, and at this line they are getting dropped.

Compare the counts for ethnicity in these two calls with our test data; I would expect them to be the same but they're not.

```
create_demographics_table(
  data,
  demographics = c("ethnic")
)

create_demographics_table(
  data,
  demographics = c("height", "ethnic")
)
```

2023-11-02 03:43 UTC, roninsightrx commented on R/create_demographics_table.R
> +        merge(vitals)
good catch. Turned into left join.

2023-11-02 03:44 UTC, roninsightrx commented on R/create_demographics_table.R
> +      dplyr::select(continuous) %>%
👍🏻 moved the "ungroup" call a few lines up.

2023-11-02 17:06 UTC, karawoo approved these changes
LGTM for our test data, but do we need to anticipate cases where we have subjects in `vs` that aren't in `dm`? Maybe we should consider a full join?

2023-11-02 17:16 UTC, merged